"""nullables

Revision ID: 12b8b02663d6
Revises: 7453c1325904
Create Date: 2022-11-13 19:01:39.942609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12b8b02663d6"
down_revision = "7453c1325904"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("staff", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("superuser", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("superuser", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("staff", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
