"""Machine data, Documents

Revision ID: 59e00562c9e4
Revises: 18df4dbd19c1
Create Date: 2022-11-15 16:08:23.386500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59e00562c9e4"
down_revision = "18df4dbd19c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "svs_document",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_svs_document")),
    )
    with op.batch_alter_table("svs_machine", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("direction", sa.String(length=10), nullable=False)
        )
        batch_op.add_column(sa.Column("instalation_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("svs_machine", schema=None) as batch_op:
        batch_op.drop_column("instalation_date")
        batch_op.drop_column("direction")
        batch_op.drop_column("model")

    op.drop_table("svs_document")
    # ### end Alembic commands ###
