"""Document

Revision ID: d0886f658ce3
Revises: 59e00562c9e4
Create Date: 2022-11-17 21:11:25.922385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0886f658ce3"
down_revision = "59e00562c9e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("svs_document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("path", sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column("category", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("machine_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_svs_document_machine_id_svs_machine"),
            "svs_machine",
            ["machine_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("svs_document", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_svs_document_machine_id_svs_machine"), type_="foreignkey"
        )
        batch_op.drop_column("machine_id")
        batch_op.drop_column("category")
        batch_op.drop_column("path")

    # ### end Alembic commands ###
